# permissions for end users to view deploytenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: deploy-operator
    app.kubernetes.io/managed-by: kustomize
  name: deploytenant-viewer-role
rules:
- apiGroups:
  - webapp.brbarmex
  resources:
  - deploytenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.brbarmex
  resources:
  - deploytenants/status
  verbs:
  - get
