---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webapp.brbarmex
  resources:
  - deploytenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.brbarmex
  resources:
  - deploytenants/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.brbarmex
  resources:
  - deploytenants/status
  verbs:
  - get
  - patch
  - update
